# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ui.myQrc


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(609, 330)
        dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        dialog.setWindowIcon(icon)
        self.btn_login = QtWidgets.QPushButton(dialog)
        self.btn_login.setGeometry(QtCore.QRect(210, 220, 101, 41))
        self.btn_login.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.52, y1:1, x2:0.54, y2:0, stop:0.0112994 rgba(64, 145, 252, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border:0px groove gray;border-radius:\n"
"7px;padding:2px 4px;\n"
"font: 14pt \"Candara\";")
        self.btn_login.setObjectName("btn_login")
        self.lineEdit_username = QtWidgets.QLineEdit(dialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(20, 160, 291, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrainsMonoMedium Nerd Font Mono")
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"border:1px groove gray;border-radius:\n"
"7px;padding:2px 4px;")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_username.setReadOnly(False)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 211, 61))
        self.label_2.setStyleSheet("font: 87 20pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(330, 0, 410, 330))
        self.label.setStyleSheet("background-image:url(:/src/blue.png);\n"
"border-radius:10px;\n"
"padding:2px 4px;")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "登录"))
        self.btn_login.setText(_translate("dialog", "Sign in"))
        self.label_2.setText(_translate("dialog", "Login now"))
